# Analisi dimensioni di qualità dei dataset originali

Questo notebook presenta l'analisi di qualità dei dati per i dataset originali, nell'ordine:

- il dataset sulla produzione di CO2
- il dataset sul consumo di carburanti fossili (benzine e gasolio)
- il dataset sul consumo di carbone
- il dataset sull'energia pulita utilizzata
- i dati sulla popolazione

Per prima cosa, importiamo i necessari pacchetti Python e carichiamo i dati

In [1]:
import pandas as pd

In [2]:
co2 = pd.read_csv("./Dataset/Puliti_da_usare/CO2_cleaned.csv")
carbone = pd.read_csv("./Dataset/Puliti_da_usare/Charcoal_UNData.csv")
carburanti = pd.read_csv("./Dataset/Puliti_da_usare/Gas and Diesel 2011-2016.csv", sep=";", quotechar='"')
energia_pulita = pd.read_csv("./Dataset/Puliti_da_usare/renewable_energy_consumption.csv", sep=";", quotechar='"')
popolazione = pd.read_csv("./Dataset/Puliti_da_usare/Population.csv", sep=";", quotechar='"')
nomi_codici_paesi = pd.read_csv("./Dataset/Puliti_da_usare/Country-codes-v1.csv", sep=";", quotechar='"')
gdp = pd.read_csv("./Dataset/finali/PIL.csv", sep=";", quotechar='"')
polveri_sottili = pd.read_csv("./Dataset/finali/Polveri sottili.csv", sep=";", quotechar='"')

Creiamo delle funzioni helper che calcolino la completezza degli attributi, delle tuple e della tabella di un generico dataset:

In [3]:
def completezza_attributi(dataset):
    """Calcola la completezza degli attributi di un dataset."""
    totale = dataset.shape[0]
    non_nulli = dataset.count()
    
    return non_nulli, totale

In [4]:
def completezza_tuple(dataset):
    """Calcola la completezza di tupla di un dataset."""
    num_attributi = dataset.shape[1]
    num_null_in_tupla = [row.isnull().count() for row in dataset]
    
    return num_null_in_tupla

In [5]:
def completezza_tabella(dataset):
    """Calcola la completezza di tabella in un dataset."""
    totali_non_null = dataset.count().sum()
    totali = dataset.shape[0] * dataset.shape[1]
    
    return totali_non_null, totali

## Completezza di tabella

Vediamo la completezza a livello di tabella per tutti i dataset:

In [6]:
tutti_dataset = {"CO2": co2, "carbone": carbone, "carburanti": carburanti,
                "energia_pulita": energia_pulita, "popolazione": popolazione,
                "nomi_codici_paesi": nomi_codici_paesi,
                "GDP": gdp,
                "Polveri sottili": polveri_sottili}

In [7]:
for nome_dataset in tutti_dataset:
    dataset = tutti_dataset[nome_dataset]
    totali_non_null, totali = completezza_tabella(dataset)
    print("Dataset '{}'".format(nome_dataset))
    print("Completezza di tabella: {:4.2f}%, con {} elementi non nulli su {} totali\n"
          .format((totali_non_null / totali) * 100, totali_non_null, totali))

Dataset 'CO2'
Completezza di tabella: 76.87%, con 2669 elementi non nulli su 3472 totali

Dataset 'carbone'
Completezza di tabella: 92.58%, con 23108 elementi non nulli su 24960 totali

Dataset 'carburanti'
Completezza di tabella: 85.64%, con 118659 elementi non nulli su 138558 totali

Dataset 'energia_pulita'
Completezza di tabella: 96.05%, con 4818 elementi non nulli su 5016 totali

Dataset 'popolazione'
Completezza di tabella: 94.58%, con 4994 elementi non nulli su 5280 totali

Dataset 'nomi_codici_paesi'
Completezza di tabella: 96.59%, con 1443 elementi non nulli su 1494 totali

Dataset 'GDP'
Completezza di tabella: 90.17%, con 4999 elementi non nulli su 5544 totali

Dataset 'Polveri sottili'
Completezza di tabella: 48.92%, con 2712 elementi non nulli su 5544 totali

## Completezza degli attributi

Per ogni dataset, vediamo ora la completezza dei suoi attributi:

In [8]:
for nome_dataset in tutti_dataset:
    dataset = tutti_dataset[nome_dataset]
    non_nulli, totale = completezza_attributi(dataset)
    print("#------ Dataset '{}' -------------------------#".format(nome_dataset))
    print("Shape ({}, {}) completezza sugli attributi:"
          .format(dataset.shape[0], dataset.shape[1]))
    print(non_nulli / totale)
    print("\nNumero di tuple con attributo non nullo (su {}):".format(dataset.shape[0]))
    print(non_nulli)
    print("\n\n")

#------ Dataset 'CO2' -------------------------#
Shape (217, 16) completezza sugli attributi:
Series Name      1.000000
Series Code      1.000000
Country Name     1.000000
Country Code     1.000000
1990 [YR1990]    0.797235
2000 [YR2000]    0.917051
2008 [YR2008]    0.935484
2009 [YR2009]    0.935484
2010 [YR2010]    0.935484
2011 [YR2011]    0.935484
2012 [YR2012]    0.949309
2013 [YR2013]    0.949309
2014 [YR2014]    0.944700
2015 [YR2015]    0.000000
2016 [YR2016]    0.000000
2017 [YR2017]    0.000000
dtype: float64

Numero di tuple con attributo non nullo (su 217):
Series Name      217
Series Code      217
Country Name     217
Country Code     217
1990 [YR1990]    173
2000 [YR2000]    199
2008 [YR2008]    203
2009 [YR2009]    203
2010 [YR2010]    203
2011 [YR2011]    203
2012 [YR2012]    206
2013 [YR2013]    206
2014 [YR2014]    205
2015 [YR2015]      0
2016 [YR2016]      0
2017 [YR2017]      0
dtype: int64



#------ Dataset 'carbone' -------------------------#
Shape (4160, 6) completezza sugli attributi:
Country or Area            1.000000
Commodity - Transaction    1.000000
Year                       1.000000
Unit                       1.000000
Quantity                   1.000000
Quantity Footnotes         0.554808
dtype: float64

Numero di tuple con attributo non nullo (su 4160):
Country or Area            4160
Commodity - Transaction    4160
Year                       4160
Unit                       4160
Quantity                   4160
Quantity Footnotes         2308
dtype: int64



#------ Dataset 'carburanti' -------------------------#
Shape (23093, 6) completezza sugli attributi:
Country or Area            1.00000
Commodity - Transaction    1.00000
Year                       1.00000
Unit                       1.00000
Quantity                   1.00000
Quantity Footnotes         0.13831
dtype: float64

Numero di tuple con attributo non nullo (su 23093):
Country or Area            23093
Commodity - Transaction    23093
Year                       23093
Unit                       23093
Quantity                   23093
Quantity Footnotes          3194
dtype: int64



#------ Dataset 'energia_pulita' -------------------------#
Shape (264, 19) completezza sugli attributi:
Country Name      1.000000
Country Code      1.000000
Indicator Name    1.000000
Indicator Code    1.000000
2000              0.931818
2001              0.935606
2002              0.943182
2003              0.943182
2004              0.943182
2005              0.946970
2006              0.946970
2007              0.954545
2008              0.954545
2009              0.954545
2010              0.954545
2011              0.954545
2012              0.962121
2013              0.962121
2014              0.962121
dtype: float64

Numero di tuple con attributo non nullo (su 264):
Country Name      264
Country Code      264
Indicator Name    264
Indicator Code    264
2000              246
2001              247
2002              249
2003              249
2004              249
2005              250
2006              250
2007              252
2008              252
2009              252
2010              252
2011              252
2012              254
2013              254
2014              254
dtype: int64



#------ Dataset 'popolazione' -------------------------#
Shape (264, 20) completezza sugli attributi:
Country Name    1.000000
Country Code    1.000000
2000            0.996212
2001            0.996212
2002            0.996212
2003            0.996212
2004            0.996212
2005            0.996212
2006            0.996212
2007            0.996212
2008            0.996212
2009            0.996212
2010            0.996212
2011            0.996212
2012            0.992424
2013            0.992424
2014            0.992424
2015            0.992424
2016            0.992424
2017            0.000000
dtype: float64

Numero di tuple con attributo non nullo (su 264):
Country Name    264
Country Code    264
2000            263
2001            263
2002            263
2003            263
2004            263
2005            263
2006            263
2007            263
2008            263
2009            263
2010            263
2011            263
2012            262
2013            262
2014            262
2015            262
2016            262
2017              0
dtype: int64



#------ Dataset 'nomi_codici_paesi' -------------------------#
Shape (249, 6) completezza sugli attributi:
official_name_en     1.000000
ISO3166-1-Alpha-3    1.000000
CLDR display name    1.000000
FIFA                 0.951807
IOC                  0.907631
ITU                  0.935743
dtype: float64

Numero di tuple con attributo non nullo (su 249):
official_name_en     249
ISO3166-1-Alpha-3    249
CLDR display name    249
FIFA                 237
IOC                  226
ITU                  233
dtype: int64



#------ Dataset 'GDP' -------------------------#
Shape (264, 21) completezza sugli attributi:
Country Name      1.000000
Country Code      1.000000
Indicator Name    1.000000
2000              0.928030
2001              0.928030
2002              0.943182
2003              0.943182
2004              0.946970
2005              0.946970
2006              0.950758
2007              0.950758
2008              0.946970
2009              0.943182
2010              0.946970
2011              0.946970
2012              0.931818
2013              0.935606
2014              0.928030
2015              0.924242
2016              0.893939
2017              0.000000
dtype: float64

Numero di tuple con attributo non nullo (su 264):
Country Name      264
Country Code      264
Indicator Name    264
2000              245
2001              245
2002              249
2003              249
2004              250
2005              250
2006              251
2007              251
2008              250
2009              249
2010              250
2011              250
2012              246
2013              247
2014              245
2015              244
2016              236
2017                0
dtype: int64



#------ Dataset 'Polveri sottili' -------------------------#
Shape (264, 21) completezza sugli attributi:
Country Name      1.000000
Country Code      1.000000
Indicator Name    1.000000
2000              0.909091
2001              0.000000
2002              0.000000
2003              0.000000
2004              0.000000
2005              0.909091
2006              0.000000
2007              0.000000
2008              0.000000
2009              0.000000
2010              0.909091
2011              0.909091
2012              0.909091
2013              0.909091
2014              0.909091
2015              0.909091
2016              0.000000
2017              0.000000
dtype: float64

Numero di tuple con attributo non nullo (su 264):
Country Name      264
Country Code      264
Indicator Name    264
2000              240
2001                0
2002                0
2003                0
2004                0
2005              240
2006                0
2007                0
2008                0
2009                0
2010              240
2011              240
2012              240
2013              240
2014              240
2015              240
2016                0
2017                0
dtype: int64